export const USERID = localStorage.getItem('userId')


export const OPEN_ADD_RECORD_OVERLAY = 'OPEN_ADD_RECORD_OVERLAY'
export const CLOSE_ADD_RECORD_OVERLAY = 'CLOSE_ADD_RECORD_OVERLAY'
export const SHOW_PRELOADER = 'SHOW_PRELOADER'
export const HIDE_PRELOADER = 'HIDE_PRELOADER'


export const ADD_RECORD = 'ADD_RECORD'
export const REMOVE_RECORD = 'REMOVE_RECORD'
export const FETCH_RECORD = 'FETCH_RECORD'

export const SHOW_SETTINGS_OVERLAY = 'SHOW_SETTINGS_OVERLAY'
export const HIDE_SETTINGS_OVERLAY = 'HIDE_SETTINGS_OVERLAY'
export const FETCH_DATA = 'FETCH_DATA'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'
export const SHOW_SETTINGS_PRELOADER = 'SHOW_SETTINGS_PRELOADER'
export const HIDE_SETTINGS_PRELOADER = 'HIDE_SETTINGS_PRELOADER'

export const SHOW_VIEW_OVERLAY = 'SHOW_VIEW_OVERLAY'
export const HIDE_VIEW_OVERLAY = 'HIDE_VIEW_OVERLAY'
export const SHOW_VIEW_PRELOADER = 'SHOW_VIEW_PRELOADER'
export const HIDE_VIEW_PRELOADER = 'HIDE_VIEW_PRELOADER'
export const FETCH_VIEW_RECORDS = 'FETCH_VIEW_RECORDS'
export const ADD_VIEW_RECORD = 'ADD_VIEW_RECORD'
export const REMOVE_VIEW_RECORD = 'REMOVE_VIEW_RECORD'
export const SHOW_VIEW_FORM = 'SHOW_VIEW_FORM'
export const HIDE_VIEW_FORM = 'HIDE_VIEW_FORM'
export const ADD_RECORD_ID = 'ADD_RECORD_ID'